version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      http.cors.enabled: 'true'
      http.cors.allow-origin: "*"

networks:
  default:
    name: elasticsearch